# SPDX-License-Identifier: LGPL-2.1-only
# Copyright (C) 2026 Kajetan R. Gulaj
# Created: 2026-07-03

"""pySMESH — standalone SMESH ViscousLayers + OCCT same-domain healing bindings.

Public surface: :func:`load_brep`, :class:`Shape`, :class:`Mesh`, and the per-entity info
types for geometry query and surface-mesh injection; :func:`compute_viscous_layers` (with
:class:`VLParams` / :class:`VLResult` / :class:`ExtrusionMethod`) for boundary-layer prism
generation; :func:`unify_same_domain` (with :class:`UnifyParams` / :class:`UnifyResult`) for
B-rep same-domain face/edge merging; and :class:`PysmeshError` for every library failure, with
:class:`PysmeshCancelled` for the subset a caller stopped.

Import-time contract: ``_core`` links VTK dynamically against whatever VTK the host
process provides. The build was compiled against a specific VTK version; importing into an
environment with a different VTK is an ABI hazard, so the version is hard-checked here and
raises :class:`ImportError` on mismatch rather than risking a silent crash.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

from . import _build_info

# --- Locate the dynamic dependencies (VTK/OCCT/Boost DLLs live in the conda env) ------- #
# conda's Python already has its Library/bin on the DLL search path; this is belt-and-
# suspenders for embedded / Nuitka hosts. It never adds a second VTK — only makes the
# host's own DLLs findable.
_dll_dir = Path(sys.prefix) / "Library" / "bin"
if _dll_dir.is_dir() and hasattr(os, "add_dll_directory"):
    os.add_dll_directory(str(_dll_dir))


def _check_vtk_version() -> None:
    """Fail loudly if the host VTK differs from the one ``_core`` was built against."""
    try:
        # VTK ships no py.typed marker; the untyped-import ignore is expected and honest.
        import vtk  # type: ignore[import-untyped]  # noqa: PLC0415 - lazy host dependency
    except ImportError as exc:  # pragma: no cover - environment-specific
        raise ImportError(
            "pysmesh requires VTK "
            f"{_build_info.VTK_VERSION} in the host environment, but VTK is not "
            "importable. Install the matching conda-forge vtk build."
        ) from exc

    host = vtk.VTK_VERSION
    if host != _build_info.VTK_VERSION:
        raise ImportError(
            "pysmesh was built against VTK "
            f"{_build_info.VTK_VERSION} but the host environment provides VTK {host}. "
            "These share an ABI-bound datastructure (vtkUnstructuredGrid); rebuild "
            "pysmesh against the host VTK or align the versions."
        )


_check_vtk_version()

from ._core import (  # noqa: E402 - must follow the VTK check
    EdgeInfo,
    FaceInfo,
    Mesh,
    PysmeshCancelled,
    PysmeshError,
    Shape,
    SolidInfo,
    VertexInfo,
    load_brep,
)
from .classify import (  # noqa: E402 - must follow the VTK check (imports _core)
    point_in_solid,
)
from .distance import (  # noqa: E402 - must follow the VTK check (imports _core)
    ShapeDistanceResult,
    free_boundary_edges,
    shape_distance,
)
from .iges import (  # noqa: E402 - must follow the VTK check (imports _core)
    IGES_UNITS,
    IgesImport,
    read_iges,
    write_iges,
)
from .mesher import (  # noqa: E402 - must follow the VTK check (imports _core)
    Adaptive1D,
    Algorithm,
    And,
    Area,
    Arithmetic1D,
    AspectRatio,
    AspectRatio3D,
    AutomaticLength,
    BLOCK_EDGE_NAMES,
    BLOCK_FACE_NAMES,
    BLOCK_VERTEX_NAMES,
    BadOrientedVolume,
    BareBorderFace,
    BareBorderVolume,
    BelongToGroup,
    Block,
    BlockParameters,
    BranchEnd,
    Cartesian3D,
    CartesianParameters3D,
    ClosestElements,
    CoincidentElements,
    CoincidentNodes,
    CompositeHexa3D,
    CompositeSegment1D,
    ComputeReport,
    Control,
    Deflection1D,
    Deflection2D,
    Distribution,
    EditReport,
    ElementDimension,
    ElementType,
    ElementsAtPoints,
    ElementsOnShape,
    EqualTo,
    FacePatches,
    FixedPoints1D,
    FreeBorders,
    FreeEdges,
    FreeFaces,
    FreeNodes,
    GMF_REQUIRED_MARKER,
    GMF_WRITABLE_TYPES,
    Geometric1D,
    GmfMesh,
    GroupSource,
    Hexa3D,
    HexaFromSkin3D,
    Hypothesis,
    LayerDistribution,
    Length,
    Length2D,
    Length3D,
    LessThan,
    LocalLength,
    ManifoldPart,
    MaxElementArea,
    MaxElementLength2D,
    MaxElementLength3D,
    MaxElementVolume,
    MaxLength,
    MedialAxis,
    MedialBranch,
    Mefisto2D,
    MergeObstruction,
    MeshData,
    MeshGroup,
    Mesher,
    MinimumAngle,
    MoreThan,
    MultiConnection,
    MultiConnection2D,
    NodeConnectivityNumber,
    Not,
    NumberOfLayers,
    NumberOfLayers2D,
    NumberOfSegments,
    Or,
    OverConstrainedFace,
    OverConstrainedVolume,
    PatternReport,
    PointState,
    PolygonPerFace2D,
    PolyhedronPerSolid3D,
    Predicate,
    Prism3D,
    ProjectedPoints,
    Projection1D,
    Projection1D2D,
    Projection2D,
    Projection3D,
    ProjectionSource1D,
    ProjectionSource2D,
    ProjectionSource3D,
    Propagation,
    QuadFromMedialAxis1D2D,
    QuadType,
    Quadrangle2D,
    QuadrangleParams,
    QuadranglePreference,
    QuadraticMesh,
    QualityResult,
    RadialPrism3D,
    RadialQuadrangle1D2D,
    RangeOfIds,
    RayHits,
    Regular1D,
    RemovalReport,
    SegmentLengthAroundVertex,
    Selection,
    SharpEdges,
    Skew,
    SlotBoundary,
    SmoothMethod,
    SplitMethod,
    StartEndLength,
    SubMeshCount,
    SubShape,
    SubShapeKind,
    Taper,
    ViscousLayers,
    ViscousLayers2D,
    Volume,
    Warping,
    block_parameters,
    block_points,
    block_shapes,
    gmf_unwritable_types,
    gmf_writable_group_name,
    medial_axis,
    quality,
    read_gmf,
    select,
    write_gmf,
)
from .offset import (  # noqa: E402 - must follow the VTK check (imports _core)
    OffsetParams,
    OffsetResult,
    ThickSolidParams,
    ThickSolidResult,
    make_thick_solid,
    offset_shape,
)
from .session import (  # noqa: E402 - must follow the VTK check (imports _core)
    AdjacencyPairs,
    BoundsTable,
    CurvatureTable,
    EntityId,
    EntityKind,
    EntityTable,
    GlueMode,
    Handoff,
    HistoryDelta,
    MassTable,
    Name,
    NameRole,
    Origin,
    Projection,
    RenderMesh,
    Resolution,
    CancelPredicate,
    ProgressCallback,
    ResolutionStatus,
    Session,
    SnapshotMark,
    SurfaceParameterTable,
    SurfaceSample,
    TypeTable,
    WireTable,
)
from .step import (  # noqa: E402 - must follow the VTK check (imports _core)
    EntityLabel,
    StepImport,
    read_step_xde,
    write_step_xde,
)
from .tessellate import (  # noqa: E402 - must follow the VTK check (imports _core)
    TessellateParams,
    TessellateResult,
    tessellate,
)
from .unify import (  # noqa: E402 - must follow the VTK check (imports _core)
    UnifyParams,
    UnifyResult,
    unify_same_domain,
)
from .viscous import (  # noqa: E402 - must follow the VTK check (imports _core)
    ExtrusionMethod,
    VLParams,
    VLResult,
    compute_viscous_layers,
)

__all__ = [
    "Adaptive1D",
    "AdjacencyPairs",
    "Algorithm",
    "And",
    "Area",
    "Arithmetic1D",
    "AspectRatio",
    "AspectRatio3D",
    "AutomaticLength",
    "BLOCK_EDGE_NAMES",
    "BLOCK_FACE_NAMES",
    "BLOCK_VERTEX_NAMES",
    "BadOrientedVolume",
    "BareBorderFace",
    "BareBorderVolume",
    "BelongToGroup",
    "Block",
    "BlockParameters",
    "BoundsTable",
    "BranchEnd",
    "CancelPredicate",
    "Cartesian3D",
    "CartesianParameters3D",
    "ClosestElements",
    "CoincidentElements",
    "CoincidentNodes",
    "CompositeHexa3D",
    "CompositeSegment1D",
    "ComputeReport",
    "Control",
    "CurvatureTable",
    "Deflection1D",
    "Deflection2D",
    "Distribution",
    "EdgeInfo",
    "EditReport",
    "ElementDimension",
    "ElementType",
    "ElementsAtPoints",
    "ElementsOnShape",
    "EntityId",
    "EntityKind",
    "EntityLabel",
    "EntityTable",
    "EqualTo",
    "ExtrusionMethod",
    "FaceInfo",
    "FacePatches",
    "FixedPoints1D",
    "FreeBorders",
    "FreeEdges",
    "FreeFaces",
    "FreeNodes",
    "GMF_REQUIRED_MARKER",
    "GMF_WRITABLE_TYPES",
    "Geometric1D",
    "GlueMode",
    "GmfMesh",
    "GroupSource",
    "Handoff",
    "Hexa3D",
    "HexaFromSkin3D",
    "HistoryDelta",
    "Hypothesis",
    "IGES_UNITS",
    "IgesImport",
    "LayerDistribution",
    "Length",
    "Length2D",
    "Length3D",
    "LessThan",
    "LocalLength",
    "ManifoldPart",
    "MassTable",
    "MaxElementArea",
    "MaxElementLength2D",
    "MaxElementLength3D",
    "MaxElementVolume",
    "MaxLength",
    "MedialAxis",
    "MedialBranch",
    "Mefisto2D",
    "MergeObstruction",
    "Mesh",
    "MeshData",
    "MeshGroup",
    "Mesher",
    "MinimumAngle",
    "MoreThan",
    "MultiConnection",
    "MultiConnection2D",
    "Name",
    "NameRole",
    "NodeConnectivityNumber",
    "Not",
    "NumberOfLayers",
    "NumberOfLayers2D",
    "NumberOfSegments",
    "OffsetParams",
    "OffsetResult",
    "Or",
    "Origin",
    "OverConstrainedFace",
    "OverConstrainedVolume",
    "PatternReport",
    "PointState",
    "PolygonPerFace2D",
    "PolyhedronPerSolid3D",
    "Predicate",
    "Prism3D",
    "ProgressCallback",
    "ProjectedPoints",
    "Projection",
    "Projection1D",
    "Projection1D2D",
    "Projection2D",
    "Projection3D",
    "ProjectionSource1D",
    "ProjectionSource2D",
    "ProjectionSource3D",
    "Propagation",
    "PysmeshCancelled",
    "PysmeshError",
    "QuadFromMedialAxis1D2D",
    "QuadType",
    "Quadrangle2D",
    "QuadrangleParams",
    "QuadranglePreference",
    "QuadraticMesh",
    "QualityResult",
    "RadialPrism3D",
    "RadialQuadrangle1D2D",
    "RangeOfIds",
    "RayHits",
    "Regular1D",
    "RemovalReport",
    "RenderMesh",
    "Resolution",
    "ResolutionStatus",
    "SegmentLengthAroundVertex",
    "Selection",
    "Session",
    "Shape",
    "ShapeDistanceResult",
    "SharpEdges",
    "Skew",
    "SlotBoundary",
    "SmoothMethod",
    "SnapshotMark",
    "SolidInfo",
    "SplitMethod",
    "StartEndLength",
    "StepImport",
    "SubMeshCount",
    "SubShape",
    "SubShapeKind",
    "SurfaceParameterTable",
    "SurfaceSample",
    "Taper",
    "TessellateParams",
    "TessellateResult",
    "ThickSolidParams",
    "ThickSolidResult",
    "TypeTable",
    "UnifyParams",
    "UnifyResult",
    "VLParams",
    "VLResult",
    "VertexInfo",
    "ViscousLayers",
    "ViscousLayers2D",
    "Volume",
    "Warping",
    "WireTable",
    "block_parameters",
    "block_points",
    "block_shapes",
    "compute_viscous_layers",
    "free_boundary_edges",
    "gmf_unwritable_types",
    "gmf_writable_group_name",
    "load_brep",
    "make_thick_solid",
    "medial_axis",
    "offset_shape",
    "point_in_solid",
    "quality",
    "read_gmf",
    "read_iges",
    "read_step_xde",
    "select",
    "shape_distance",
    "tessellate",
    "unify_same_domain",
    "write_gmf",
    "write_iges",
    "write_step_xde",
]
