"""Fail loudly if the VTK build pin has drifted from the binary that was actually built.

Two things must agree on the VTK version:

1. ``ci/environment.yml``      — the ``vtk=`` build pin (headers compiled against, DLLs bundled),
2. ``_build_info.VTK_VERSION`` — what ``_core`` was actually compiled against (generated by
   CMake; present after a build).

This is now a purely internal, self-consistency check. It catches a stale pin against the
real build within one build session.

Scope note for 4.0.0: this script used to carry a third source of truth,
``host-vtk-version.txt``, the VTK version the consuming application shipped. That check is
gone with the shared-VTK design. VTK is bundled privately into the wheel now, so no host
version exists to agree with, and a consumer is free to run any VTK, or none at all. The
pin below still matters because the headers compiled against and the DLLs bundled must come
from one environment, but it no longer couples this repo to any other.

Usage:
    python ci/check_vtk_pin.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent


def _env_pin() -> str:
    text = (_ROOT / "ci" / "environment.yml").read_text(encoding="utf-8")
    m = re.search(r"^\s*-\s*vtk\s*=\s*([0-9][0-9.]*)\s*$", text, re.MULTILINE)
    if not m:
        raise SystemExit("ci/environment.yml has no pinned 'vtk=<version>' line")
    return m.group(1)


def _build_info_pin() -> str | None:
    p = _ROOT / "src" / "pysmesh" / "_build_info.py"
    if not p.exists():
        return None
    m = re.search(r'VTK_VERSION\s*:\s*Final\[str\]\s*=\s*"([^"]+)"', p.read_text("utf-8"))
    return m.group(1) if m else None


def _check_locks(pin: str) -> None:
    """Fail unless the locks carry the pinned VTK where the build takes it from.

    A leg in ``VTK_SIDE_ENV`` (``ci/lock_envs.py``) builds against ``ci/locks/vtk-win-64.txt``
    and its own lock must have no VTK; every other leg's lock must have the pinned VTK.
    """
    from lock_envs import PYTHONS, VTK_SIDE_ENV  # ci/ is the script directory

    locks = _ROOT / "ci" / "locks"
    wanted = re.compile(r"/vtk-base-" + re.escape(pin) + r"-[^/]*$", re.MULTILINE)
    anyvtk = re.compile(r"/vtk-base-[0-9][^/]*$", re.MULTILINE)

    def urls(name: str) -> str:
        text = (locks / name).read_text(encoding="utf-8")
        return "\n".join(ln.split("#", 1)[0] for ln in text.splitlines())

    problems: list[str] = []
    for py in PYTHONS:
        lock = urls(f"build-py{py}-win-64.txt")
        if py in VTK_SIDE_ENV:
            if anyvtk.search(lock):
                problems.append(
                    f"build-py{py}: a VTK side-env leg, but its lock has VTK"
                )
        elif not wanted.search(lock):
            problems.append(f"build-py{py}: no vtk-base {pin} in the lock")
    if not wanted.search(urls("vtk-win-64.txt")):
        problems.append(f"vtk-win-64: no vtk-base {pin} in the lock")
    if problems:
        raise SystemExit("VTK lock DRIFT: " + "; ".join(problems))
    print(f"  every lock carries vtk-base {pin} where the build takes VTK from")


def main() -> None:
    env = _env_pin()
    print(f"ci/environment.yml vtk pin: {env}")
    _check_locks(env)

    build_info = _build_info_pin()
    if build_info is None:
        print("  _build_info.py absent (no build yet), skipping build-vs-pin check")
    elif build_info != env:
        raise SystemExit(f"DRIFT: _build_info VTK_VERSION={build_info} != env pin={env}")
    else:
        print(f"  matches _build_info VTK_VERSION={build_info}")

    print("VTK pin OK (build-internal; no host coupling since 4.0.0)")


if __name__ == "__main__":
    main()
    sys.exit(0)
