"""Fail loudly if the VTK pin has drifted — the only cross-repo version coupling.

Three things must agree on the VTK version:

1. ``ci/environment.yml``   — the ``vtk=`` build pin,
2. ``_build_info.VTK_VERSION`` — what ``_core`` was actually compiled against (generated by
   CMake; present after a build),
3. ``flux-vtk-version.txt``  — the version flux ships, if published into this repo.

(1) vs (2) catches a stale pin vs the real build; (3) catches drift from the host app. A
missing (2)/(3) is skipped with a notice (e.g. running before a build, or no flux pin yet).

Usage:
    python ci/check_vtk_pin.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent


def _env_pin() -> str:
    text = (_ROOT / "ci" / "environment.yml").read_text(encoding="utf-8")
    m = re.search(r"^\s*-\s*vtk\s*=\s*([0-9][0-9.]*)\s*$", text, re.MULTILINE)
    if not m:
        raise SystemExit("ci/environment.yml has no pinned 'vtk=<version>' line")
    return m.group(1)


def _build_info_pin() -> str | None:
    p = _ROOT / "src" / "pysmesh" / "_build_info.py"
    if not p.exists():
        return None
    m = re.search(r'VTK_VERSION\s*:\s*Final\[str\]\s*=\s*"([^"]+)"', p.read_text("utf-8"))
    return m.group(1) if m else None


def _flux_pin() -> str | None:
    p = _ROOT / "flux-vtk-version.txt"
    return p.read_text("utf-8").strip() if p.exists() else None


def main() -> None:
    env = _env_pin()
    print(f"ci/environment.yml vtk pin: {env}")

    build_info = _build_info_pin()
    if build_info is None:
        print("  _build_info.py absent (no build yet) — skipping build-vs-pin check")
    elif build_info != env:
        raise SystemExit(f"DRIFT: _build_info VTK_VERSION={build_info} != env pin={env}")
    else:
        print(f"  matches _build_info VTK_VERSION={build_info}")

    flux = _flux_pin()
    if flux is None:
        print("  flux-vtk-version.txt absent — skipping cross-repo check")
    elif flux != env:
        raise SystemExit(f"DRIFT: flux ships VTK {flux} but pin is {env} — rebuild pySMESH")
    else:
        print(f"  matches flux-vtk-version.txt={flux}")

    print("VTK pin OK")


if __name__ == "__main__":
    main()
    sys.exit(0)
