"""Regenerate the immutable CI environment locks from ``ci/environment.yml``.

CI never solves an environment. Every build leg installs an explicit lockfile: each package
by its exact URL and its sha256, which micromamba checks before it installs (a tampered or
replaced package aborts the job). This script is the only place that solves. Run it, review
the diff of ``ci/locks/``, and commit it with the change that needed it.

Locks written (all win-64, conda-forge only):

- ``ci/locks/build-py<X.Y>-win-64.txt``: the build env of each supported CPython.
- ``ci/locks/vtk-win-64.txt``: VTK in an env of :data:`VTK_SIDE_PYTHON`, for the legs in
  :data:`VTK_SIDE_ENV`.
- ``ci/locks/novtk-requirements.txt``: the NumPy wheel of the no-VTK check, per CPython,
  with its PyPI sha256 (installed with ``pip --require-hashes``).

Why a VTK side env: conda-forge builds VTK once per CPython, and it publishes a new CPython's
VTK weeks after the CPython itself. ``_core`` links only three VTK C++ modules (CommonCore,
CommonDataModel, FiltersVerdict). None of them, nor any DLL they load, depends on a Python
DLL. So a leg whose CPython has no VTK build yet takes VTK from an env of another CPython.
That env is :data:`VTK_SIDE_PYTHON`, the newest CPython with the pinned VTK. Once
conda-forge ships the pinned VTK for a leg, remove the leg from :data:`VTK_SIDE_ENV`.

Each env is created for real (the packages are downloaded and checked) and exported with
``conda list --explicit --sha256``. The envs are created under ``--work`` and removed after
export, except the ones named by ``--keep``.

Usage (with the miniforge base Python, no other dependency; `--only` limits the run):
    python ci/lock_envs.py --conda <conda.exe> --work <dir> [--keep 3.13 vtk] [--only vtk]
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import urllib.request
from pathlib import Path
from typing import Final

ROOT: Final[Path] = Path(__file__).resolve().parent.parent
ENV_FILE: Final[Path] = ROOT / "ci" / "environment.yml"
LOCK_DIR: Final[Path] = ROOT / "ci" / "locks"

# Keep in lockstep with `requires-python`, the classifiers and the matrix in ci.yml.
PYTHONS: Final[tuple[str, ...]] = ("3.11", "3.12", "3.13", "3.14", "3.15")
# CPythons for which conda-forge has no build of the pinned VTK yet (checked 2026-10-10).
VTK_SIDE_ENV: Final[frozenset[str]] = frozenset({"3.15"})
VTK_SIDE_PYTHON: Final[str] = "3.14"
CHANNEL: Final[str] = "conda-forge"


def specs() -> tuple[list[str], str]:
    """Return the dependency specs of environment.yml without python, and the VTK pin."""
    text = ENV_FILE.read_text(encoding="utf-8")
    body = text.split("dependencies:", 1)[1]
    out: list[str] = []
    for line in body.splitlines():
        m = re.match(r"^\s*-\s*(\S.*?)\s*(#.*)?$", line)
        if m:
            out.append(m.group(1))
    vtk = [s for s in out if re.fullmatch(r"vtk\s*=\s*[0-9.]+", s)]
    if len(vtk) != 1:
        raise SystemExit(f"{ENV_FILE}: expected one 'vtk=<version>' spec, found {vtk}")
    others = [s for s in out if not s.startswith("python ") and s != "python"]
    return others, vtk[0].split("=", 1)[1].strip()


def create_and_export(
    conda: str, prefix: Path, packages: list[str], lock: Path
) -> None:
    """Create an env at `prefix` from `packages` and export it as an explicit sha256 lock."""
    if prefix.exists():
        shutil.rmtree(prefix)
    cmd = [
        conda,
        "create",
        "-y",
        "-q",
        # conda-forge's git ships a Start-menu entry. On an all-users conda install, conda
        # asks Windows for elevation to write it; these throwaway envs need no shortcut.
        "--no-shortcuts",
        "-p",
        str(prefix),
        "--override-channels",
        "-c",
        CHANNEL,
    ]
    print(f"== {lock.name}: {' '.join(packages)}", flush=True)
    subprocess.run([*cmd, *packages], check=True)
    exported = subprocess.run(
        [conda, "list", "-p", str(prefix), "--explicit", "--sha256"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    lines = [ln for ln in exported.splitlines() if ln.startswith("https://")]
    bad = [ln for ln in lines if not re.search(r"#[0-9a-f]{64}$", ln)]
    if bad or not lines:
        raise SystemExit(f"{lock.name}: lines without a sha256: {bad[:3]}")
    header = [
        "# Generated by ci/lock_envs.py from ci/environment.yml. Do not edit by hand.",
        f"# Packages: {' '.join(packages)}",
        "# platform: win-64",
        "@EXPLICIT",
    ]
    lock.write_text("\n".join([*header, *lines]) + "\n", encoding="utf-8")


def python_check(prefix: Path, version: str) -> None:
    """Fail unless the env's interpreter is the requested, GIL-enabled CPython."""
    exe = prefix / "python.exe"
    probe = (
        "import sys, sysconfig; print('%d.%d' % sys.version_info[:2], "
        "sysconfig.get_config_var('Py_GIL_DISABLED') or 0)"
    )
    got = subprocess.run(
        [str(exe), "-c", probe],
        check=True,
        capture_output=True,
        text=True,
    ).stdout.split()
    if got != [version, "0"]:
        raise SystemExit(
            f"{prefix}: expected CPython {version} with the GIL, got {got}"
        )


def numpy_requirements(pythons: tuple[str, ...]) -> str:
    """Pin, per CPython, the newest NumPy with a win_amd64 wheel, by its PyPI sha256."""
    with urllib.request.urlopen("https://pypi.org/pypi/numpy/json", timeout=60) as r:
        releases = json.load(r)["releases"]

    def key(v: str) -> tuple[int, ...]:
        return tuple(int(x) for x in v.split("."))

    finals = sorted((v for v in releases if re.fullmatch(r"\d+\.\d+\.\d+", v)), key=key)
    lines = [
        "# Generated by ci/lock_envs.py. The NumPy of the no-VTK check, per CPython, by sha256.",
        "# Install with: pip install --require-hashes -r ci/locks/novtk-requirements.txt",
    ]
    for py in pythons:
        tag = "cp" + py.replace(".", "")
        for v in reversed(finals):
            files = [
                f
                for f in releases[v]
                if f["filename"].endswith(f"-{tag}-{tag}-win_amd64.whl")
                and not f["yanked"]
            ]
            if files:
                sha = files[0]["digests"]["sha256"]
                lines.append(
                    f'numpy=={v}; python_version == "{py}" --hash=sha256:{sha}'
                )
                break
        else:
            raise SystemExit(f"no NumPy win_amd64 wheel for {tag} on PyPI")
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--conda", required=True, help="conda executable")
    ap.add_argument("--work", required=True, type=Path, help="directory for the envs")
    ap.add_argument("--keep", nargs="*", default=[], help="envs to keep: 3.X or vtk")
    ap.add_argument(
        "--only", nargs="*", default=[], help="regenerate only these: 3.X, vtk or numpy"
    )
    args = ap.parse_args()

    others, vtk_pin = specs()
    LOCK_DIR.mkdir(exist_ok=True)
    args.work.mkdir(parents=True, exist_ok=True)

    def wanted(name: str) -> bool:
        return not args.only or name in args.only

    for py in PYTHONS:
        if not wanted(py):
            continue
        packages = [f"python={py}", *others]
        if py in VTK_SIDE_ENV:
            packages = [s for s in packages if not s.startswith("vtk=")]
        prefix = args.work / f"build-py{py}"
        create_and_export(
            args.conda, prefix, packages, LOCK_DIR / f"build-py{py}-win-64.txt"
        )
        python_check(prefix, py)
        if py not in args.keep:
            shutil.rmtree(prefix)

    if wanted("vtk"):
        # The vtk metapackage, as in the other legs: VTK's CMake package lists every module,
        # the ffmpeg IO module of vtk-io-ffmpeg included, and fails without it.
        prefix = args.work / "vtk"
        create_and_export(
            args.conda,
            prefix,
            [f"python={VTK_SIDE_PYTHON}", f"vtk={vtk_pin}"],
            LOCK_DIR / "vtk-win-64.txt",
        )
        if "vtk" not in args.keep:
            shutil.rmtree(prefix)

    if wanted("numpy"):
        reqs = numpy_requirements(PYTHONS)
        (LOCK_DIR / "novtk-requirements.txt").write_text(reqs, "utf-8")
    print("locks written to", LOCK_DIR)


if __name__ == "__main__":
    main()
    sys.exit(0)
